### PR TITLE
update:chinese translation

### PR DESCRIPTION
**Pull request by Hansen0314**

### CODE REVIEW

**Comment by Hansen0314** [comment]
@adisuciu 
    we have updated the Chinese translation. but there exists some bug as below pic.
image
image
image
image
image
image
image
image
image

**Comment by adisuciu** [comment]
I added these two commits here - https://github.com/analogdevicesinc/scopy/tree/Hansen0314-master 
These should add the translation strings that are missing
Can you update them ? It would be great if you could squash the commits before merging. If you need any help doing this, let me know.

-Adrian

**Comment by Hansen0314** [comment]
@adisuciu :
    yes, I will do this thing. can you give me the newest scopy_cn.ts?

**Comment by adisuciu** [comment]
It's in the branch i provided

**Comment by Hansen0314** [comment]
Hi @adisuciu :
   I have updated the newest Chinese translation.

**Comment by adisuciu** [comment]
Can you squash these to a single commit ?

**Comment by adisuciu** [comment]
This looks great. We want to merge this asap. You can either squash these commits or I can create another PR that contains my modifications as well alongside yours.

-Adrian

**Comment by Hansen0314** [comment]
@adisuciu : 
sorry, I do not know how to squash these commits.

**Comment by adisuciu** [comment]
I created this PR https://github.com/analogdevicesinc/scopy/pull/941 
It is based on the translation strings i provided and your translation file. I gave you credit in the commit message. If this is okay, we can merge that PR and close this one.

-Adrian

**Comment by Hansen0314** [comment]
OK

**Pull request closed without merging**
