### PR TITLE
add:Chinese 

### PR DESCRIPTION
**Pull request by Hansen0314**
scopy_cn

### CODE REVIEW

**Comment by Hansen0314** [comment]
do you have some questions for this translation?

**Comment by adisuciu** [comment]
Hi,

Thank you for your contribution. 
First of all, you need to add the translation to the qrc file, similar to what was done in this commit ( but for scopy_cn.ts) : https://github.com/analogdevicesinc/scopy/pull/811/commits/e2db4309dc58ab714574901f75b36f0b010b1c3a

Second, it looks like you used an outdated version as baseline for the translation - as you can see, there are a few strings that ar e not translated such as "Show ADC digital filter config", "Enable sample rate filters", etc.

I attached an archive containing the updated ts file
[scopy_cn.zip](https://github.com/analogdevicesinc/scopy/files/4980931/scopy_cn.zip)
Can you review it and add the missing translations and do another commit ? There are probably only a few strings that are missing.

Thanks again !
-Adrian

**Comment by Hansen0314** [comment]
Hi @adisuciu 
   when I finished the newest scopy_cn.there also exists some content that cannot translate.do you have any idea about that?
[translation fail.zip](https://github.com/analogdevicesinc/scopy/files/4986741/translation.fail.zip)

**Comment by adisuciu** [comment]
Thanks, I'm looking into it ..

**Comment by adisuciu** [comment]
This branch contains the missing strings - https://github.com/analogdevicesinc/scopy/pull/835 . We'll merge soon.

I attached the updated file .ts
[scopy_cn.zip](https://github.com/analogdevicesinc/scopy/files/4994158/scopy_cn.zip)
 file.

**Comment by adisuciu** [comment]
Updated translation file:
[scopy_cn.zip](https://github.com/analogdevicesinc/scopy/files/4994849/scopy_cn.zip)

-Adrian

**Comment by Hansen0314** [comment]
Hi @adisuciu 
   we have updated the Chinese translation. but there exists some bug as below pic.
image
image
image

**Comment by adisuciu** [comment]
The info page will not be translated, as some of the info comes from the hardware.
I traced down the bugs in the second and third screenshot and a fix will be available soon.

Also when we merge the spectral measurements and mixed signal view, there will be a few more strings to be translated (not many). I'll let you know when those are merged.

-Adrian

**Comment by adisuciu** [comment]
[scopy_cn.zip](https://github.com/analogdevicesinc/scopy/files/5154539/scopy_cn.zip)

I updated your .ts file according to the newest translation strings in master. We can merge after updating it.

Thanks,
-Adrian

**Comment by AlexandraTrifan** [comment]
We are creating a release candidate so I will merge this into master as it is. 
Once you update the translation using the latest scopy_cn.zip that Adrian provided, you can create another Pull Request and we will add that to master as well.

Thank you,
-Alexandra

**Review by AlexandraTrifan — APPROVED** [review]

**Pull request merged**
