### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by DanielGuramulta**
This pull request implements enhancements for the Logic tools as described in the following issues:
- #961 
- #958 
- #949 (w/o the plotting artefact)

### CODE REVIEW

**Review by AlexandraTrifan — APPROVED** [review]
Looks good!

**Comment by DanielGuramulta** [comment]
I have pushed some few new changes, @AlexandraTrifan could you review this new changes? Thank you!

**Comment by AlexandraTrifan** [comment]
> I have pushed some few new changes, @AlexandraTrifan could you review this new changes? Thank you!

Looks good! I will give it a test run once a appveyor build is finished.

**Comment by DanielGuramulta** [comment]
Should be in final form with all the enhancements. @AlexandraTrifan could you take another look at this. Thank you!

**Comment by AlexandraTrifan** [comment]
Looks good!

**Review by AlexandraTrifan — APPROVED** [review]

**Pull request merged**
